# config/local.yaml

environment: "local" # Окружение - local, dev или prod
storage_path: "./storage.db" # файл, в котором будет храниться наша БД
log_level: "debug"
http_server: # конфигурация нашего http-сервера
  address: "localhost"
  port: 8080
  timeout: "4s"
  idle_timeout: "30s"